from typing import Optional, Protocol, Any, Dict

class ILiqiHandler(Protocol):
    def input(self, liqi_msg: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def get_pending_reaction(self) -> Optional[Dict[str, Any]]: ...